### ISSUE TITLE
请问这个有数据库脚本吗？

### ISSUE THREAD

**Issue by lucas-core** [leosanqing/go_foodie_shop#14]
您好，我也刚学go不久，想研究下您这个项目，请问一下又没有数据库的脚本文件。

**Comment by leosanqing** [comment]
有的  因为刚开始，一直在实现接口，所以文档以及数据库方面的还没有维护，已经上传了，在项目 sql 目录下

**Comment by lucas-core** [comment]
好的，谢谢你。
